package br.gov.interpretaai.server.core;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.Timestamp;
import java.time.Duration;
import java.time.Instant;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class OperationalOutboxStoreTest {
    private JdbcTemplate jdbc;
    private OperationalOutboxStore store;

    @BeforeEach
    void prepareDatabase() {
        var dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                create table operational_outbox (
                    id bigint generated by default as identity primary key,
                    event_type varchar(64) not null,
                    status varchar(16) not null,
                    attempts integer not null default 0,
                    available_at timestamp with time zone not null,
                    created_at timestamp with time zone not null
                )
                """);
        store = new OperationalOutboxStore(jdbc);
    }

    @Test
    void leasePreventsTheSameEventFromBeingClaimedTwice() {
        Instant now = Instant.parse("2026-09-14T12:00:00Z");
        insert(now);

        var first = store.claimNext(now, Duration.ofSeconds(30));
        var duplicate = store.claimNext(now, Duration.ofSeconds(30));

        assertThat(first).isPresent();
        assertThat(duplicate).isEmpty();
        assertThat(status(first.orElseThrow().id())).isEqualTo("PROCESSING");
    }

    @Test
    void appliesBackoffAndMovesPoisonEventToDeadAfterFiveAttempts() {
        Instant now = Instant.parse("2026-09-14T12:00:00Z");
        insert(now);

        for (int expectedAttempts = 1; expectedAttempts <= 5; expectedAttempts++) {
            var event = store.claimNext(now, Duration.ofSeconds(30)).orElseThrow();
            store.retry(event, now);
            Integer attempts = jdbc.queryForObject(
                    "select attempts from operational_outbox where id = ?", Integer.class, event.id());
            assertThat(attempts).isEqualTo(expectedAttempts);
            assertThat(status(event.id())).isEqualTo(expectedAttempts == 5 ? "DEAD" : "PENDING");
            now = now.plusSeconds(61);
        }

        assertThat(store.claimNext(now, Duration.ofSeconds(30))).isEmpty();
    }

    private void insert(Instant now) {
        jdbc.update("""
                insert into operational_outbox(event_type, status, attempts, available_at, created_at)
                values ('VOICE_TURN_COMPLETED', 'PENDING', 0, ?, ?)
                """, Timestamp.from(now), Timestamp.from(now));
    }

    private String status(long id) {
        return jdbc.queryForObject(
                "select status from operational_outbox where id = ?", String.class, id);
    }
}
