create table media_upload_session (
    media_id varchar(64) primary key,
    school_id varchar(64) not null references institution_school(school_id),
    owner_user_id varchar(64) not null references institution_adult_user(user_id),
    idempotency_key varchar(128) not null,
    request_fingerprint varchar(64) not null,
    original_file_name varchar(160) not null,
    media_type varchar(32) not null check (media_type in ('image/jpeg', 'image/png', 'image/webp')),
    declared_bytes bigint not null check (declared_bytes between 1 and 10485760),
    status varchar(24) not null check (status in ('PENDING_UPLOAD', 'UPLOADED', 'EXPIRED', 'FAILED')),
    object_key varchar(255) not null,
    actual_bytes bigint,
    sha256 varchar(64),
    expires_at timestamp with time zone not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    unique (owner_user_id, school_id, idempotency_key)
);

create index idx_media_upload_owner
    on media_upload_session (owner_user_id, school_id, status, expires_at);

create table institution_audit_event (
    audit_id bigint generated by default as identity primary key,
    actor_user_id varchar(64) not null references institution_adult_user(user_id),
    school_id varchar(64) not null references institution_school(school_id),
    action varchar(64) not null,
    target_type varchar(64) not null,
    target_id varchar(64) not null,
    occurred_at timestamp with time zone not null
);

create index idx_institution_audit_school_time
    on institution_audit_event (school_id, occurred_at, audit_id);
