alter table story_version
    add column min_app_version integer not null default 1
    check (min_app_version >= 1);

create table story_assignment (
    assignment_id varchar(64) primary key,
    school_id varchar(64) not null references institution_school(school_id),
    story_id varchar(64) not null,
    story_version integer not null,
    classroom_id varchar(64) not null references institution_classroom(classroom_id),
    created_by_user_id varchar(64) not null references institution_adult_user(user_id),
    idempotency_key varchar(128) not null,
    request_fingerprint varchar(64) not null,
    priority integer not null check (priority between 0 and 100),
    status varchar(16) not null check (status in ('ACTIVE', 'REVOKED')),
    delivery_sequence bigint generated by default as identity,
    available_from timestamp with time zone not null,
    expires_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    foreign key (story_id, story_version) references story_version(story_id, version),
    unique (created_by_user_id, school_id, idempotency_key),
    check (expires_at is null or expires_at > available_from)
);

create index idx_story_assignment_device_manifest
    on story_assignment (school_id, classroom_id, status, delivery_sequence);
