create table operational_outbox (
    id bigint generated by default as identity primary key,
    event_type varchar(64) not null,
    status varchar(16) not null,
    attempts integer not null default 0,
    available_at timestamp with time zone not null,
    created_at timestamp with time zone not null
);

create index idx_operational_outbox_ready
    on operational_outbox (status, available_at, id);
