create table pilot_learning_event (
    event_id varchar(64) primary key,
    device_id varchar(64) not null,
    classroom_id varchar(64) not null,
    learner_alias varchar(12) not null,
    activity_id varchar(64) not null,
    event_type varchar(32) not null,
    modality varchar(16) not null,
    duration_ms bigint,
    observation_category varchar(32) not null,
    occurred_at timestamp with time zone not null,
    received_at timestamp with time zone not null
);

create index idx_pilot_learning_event_classroom
    on pilot_learning_event (classroom_id, occurred_at);

create table pilot_administrative_access_audit (
    id bigint generated by default as identity primary key,
    access_role varchar(16) not null,
    resource_scope varchar(80) not null,
    accessed_at timestamp with time zone not null
);

create index idx_pilot_admin_audit_time
    on pilot_administrative_access_audit (accessed_at);
